const her = {
    id: 1,
    pathway: 'her',
    title1: 'Her',
    title2: {
        introduction: 'Introduction',
        solitude: 'La solitude',
        rouge: 'Le rouge',
        jaune: 'Le jaune',
        blanc: 'Le blanc',
        grosPlans: 'Les gros plans',
        hibou: 'Le hibou',
        directeurPhoto: 'Hoyte Van Hoytema',
        conslusion: 'Conclusion',
        bonus: 'Bonus',
    },
    title3: {
        synopsis: 'Synopsis',
    },
    paragraphe: {
        paragraphe1: 'L\'histoire se déroule à Los Angeles dans un futur proche. Théodore vie difficilement la rupture qu\'il a eu avec sa femme. Un jour, il fait l\'acquisition d\'une application ultra-moderne qui est capable de s\'adapter à la personnalité de l\'utilisateur et qui se présente sous le nom de Samantha. Si vous voulez c\'est comme Siri, mais avec la voix de Scarlett Johansson. Cette Samantha s\'avère être très intelligente et drôle, à tel point qu\'il en tombe amoureux.',
        paragraphe2: 'Le film “Her” commence avec lui, Théodore Twombly interprété par Joaquin Phoenix.',
        paragraphe3: 'Le plan est très serré et l\'on note la présence du rouge, deux éléments qui reviendrons tout au long du film.',
        paragraphe4: 'Les plans larges seront minoritaires et uniquement là pour montrer le contexte dans lequel les personnages évoluent. Comme le plan ci-dessous qui montre de façon suggéré l\'isolement des individus malgré leur proximité.',
        paragraphe5: 'Remarquez comme tous les personnages marchent seuls.',
        paragraphe6: 'Pour ancrer dans notre esprit que Théodore est un individu qui se sent terriblement seul, Spike Jonze, le réalisateur du film, a créé une scène très simple.',     
        paragraphe7: 'Théodore est chez lui, il vient d\'installer son application et il fait la connaissance de Samantha, celle-ci lui propose de faire un tri dans ses emails. Le plan est rapproché, on s\'attarde sur les émotions de Théodore qui est surprit et amusé par cette nouvelle application. Puis démarre cette discussion :',
        paragraphe8: '“- J\'aimerais trier vos contacts. Hé vous avez beaucoup de contacts.',
        paragraphe9: '- Je suis très populaire.',
        paragraphe10: '- Vraiment ? Ça veut dire que vous avez des amis ?',
        paragraphe11: '- (rire) Vous m\'avez bien cerné.”',
        paragraphe12: 'Théodore se dit très populaire, mais dès lors que cet échange démarre, le plan change pour nous donner une vue plus large de son appartement vide, la caméra continuant à reculer lentement.',
        paragraphe13: 'La couleur rouge. Lorsqu\'on l\'évoque on pense à la passion. Et comme la passion, la couleur rouge possède un paradoxe que nul autre couleur ne possède. Elle joue avec les opposés, comme par exemple : L\'amour et la colère, la sensualité et la sexualité, le courage et le danger etc...',
        paragraphe14: 'Dans la quasi-totalité des plans, on y remarque sa présence. Couleur que l\'on retrouve bien souvent sur les épaules de Théodore. Sur un vêtement porté par une tierce personne ou encore sur un élément du décor',
        paragraphe15: 'Le jaune est aussi une couleur chaude, associé aux rayons du soleil qui apporte la vie, la joie, la chaleur. Elle est aussi souvent associée à la traitrise, au mensonge et à la tromperie. Vous avez surement déjà entendu le therme “jaune cocu”. Dans “Her” j\'ai remarqué l\'apparition de cette couleur dans les chemises de Théodore qu\'à trois reprises.',
        paragraphe16: 'Dans deux de ces trois scènes, il s\'agissait de scène qui traitait plus ou moins d\'infidélité.',
        paragraphe17: 'Dans la première, il est en rencard avec une femme, mais bien que célibataire, il est encore très amoureux de son ex-femme.',
        paragraphe18: 'Dans une autre, il découvre que Samantha discute avec un nombre important d\'autres personnes sur internet et qu\'elle entretient des “relations” avec certaines d\'entre elles.',
        paragraphe19: 'Pour la dernière, je n\'ai pas remarqué de point commun. Dans cette scène il discute avec une petite fille de 4 ans et lui explique qu\'il parle avec Samantha, une fille qui vit dans un ordinateur.',
        paragraphe20: 'Ça remet peut-être ma théorie des couleurs en doute. Je veux bien que vous m\'aidiez à éclaircir se mystère.',
        paragraphe21: 'Le blanc ne possède pas de signification négative. Au contraire, cette “couleur” représente la pureté, l\'innocence, la virginité.',
        paragraphe22: 'Lors de la scène de fin, Théodore a endossé sa plus belle chemise blanche. Peut-être ne le sait-il pas, mais il est parvenu à faire le deuil de sa relation avec son ex-femme.',
        paragraphe23: 'Dans cette même scène où il est sur le toit de son immeuble avec sa voisine et amie, interprétée par Amy Adams. On le voit d\'abord errer seul avant de la rejoindre pour s\'assoir à ses côtés. Sa voisine est habillée d\'un pull rouge, je ne vous l\'ai pas dit, mais le rouge est aussi la couleur du triomphe.',
        paragraphe24: 'Dans “Her” les gros plans et très gros plans sont plus nombreux qu\'à l\'accoutumé. Le film se basant sur une histoire d\'amour, le réalisateur a décidé de se focaliser sur l\'histoire personnelle de Théodore et sur ce qu\'il ressent tout au long du film. Ces plans permettent également de l\'isoler du monde extérieur, accentuant la bulle dans laquelle il est tout au long du film.',
        paragraphe25: 'A la suite d\'une dispute, Théodore part se promener seul dans la rue. Alors qu\'il est assis sur un muret un écran derrière lui diffuse l\'image d\'une chouette attrapant sa proie. Depuis l\'angle de vu choisi par le réalisateur, le rapace semble avoir choisi pour cible le protagoniste du film.',
        paragraphe26: 'J\'ai longuement réfléchi à la signification de ce plan. Théodore se fait attraper ? Qui/Quoi l\'attrape ? Ce que j\'en ai compris c\'est que cette chouette l\'extirpe de son isolement. En effet c\'est à ce moment précis du film, après la dispute, que la situation commence à changer pour lui.',
        paragraphe27: 'Les problématiques liés à son idylle avec Samantha vont peu à peu s\'intensifier et le faire redescendre sur terre.',
        paragraphe28: 'Ah, et pour info, pour différencier un hibou d\'une chouette il faut regarder les “sourcils”. Les chouettes ont des yeux bien ronds alors que les hiboux ont des gros “sourcils” formant presque des cornes et leurs donnant un air presque tout le temps en colère et prêt à dévorer votre âme.',
        paragraphe29: 'Comment parler de la photographie de ce film sans parler de Hoyte Van Hoytema. Il a été le directeur de la photograhie pour ce film. Vous connaissez forcément son travail car il a également travaillé sur des films très célèbre comme Spectre, Tenet, Interstallar, Dunkerque et bien plus.',
        paragraphe30: 'Dans cette conclusion je voulais vous parler de l\'importance de regarder ce film en Version originale.',
        paragraphe31: 'Dans la version française, l\'actrice qui réalise le doublage parle normalement dans ses scènes. Alors que dans la version originale, Scarlett Johansson qui fait la voix de Samantha, à une voix très douce, elle donne l\'impression de souvent chuchoter, il y a un petit côté ASMR, elle possède aussi un timbre de voix un peu cassé. Pour rappel Samantha n\'est pas présente à l\'image, on ne fait qu\'entendre sa voix, donc ses émotions ne passent que par là.',
        paragraphe32: 'Pour vous convaincre je vous partage une chanson interprétée par Scarlett Johansson dans le film :',
        paragraphe33: 'Les paroles :',
        paragraphe34: 'I\'m lying on the moon',
        paragraphe35: 'My dear, I\'ll be there soon',
        paragraphe36: 'It\'s a quiet and starry place',
        paragraphe37: 'Time\'s we\'re swallowed up',
        paragraphe38: 'In space we\'re here a million miles away',
        paragraphe39: 'There\'s things I wish I knew',
        paragraphe40: 'There\'s no thing I keep from you',
        paragraphe41: 'It\'s a dark and shiny place',
        paragraphe42: 'But with you my dear',
        paragraphe43: 'I\'m safe and we\'re a million miles away',
        paragraphe44: 'Pour les plus fidèles qui lisent jusqu\'à la fin je voulais vous partager en texte un extrait de la meilleure scène de “phone sex” que le cinéma n\'est jamais connu :',
        paragraphe45: '“- Je te sens... Etrangle-moi avec le chat mort',
        paragraphe46: '- Quoi ?',
        paragraphe47: '- Le chat mort, posé près du lit. Etrangle-moi avec.',
        paragraphe48: '- ….heuuu... Okay',
        paragraphe49: '- Allez, dis-le.',
        paragraphe50: '- Je t\'étrangle avec le chat... Je serre encore. Le chat est mort....”'
    },
    picture: {
        img1: {
            img: '/assets/imgArticles/Her/1.jpg',
            alt: 'gros plan sur Joaquin Phoenix',
        },
        img2: {
            img: '/assets/imgArticles/Her/3.jpg',
            alt: 'gros plan sur Joaquin Phoenix',
        },
        img3: {
            img: '/assets/imgArticles/Her/3.jpg',
            alt: 'gros plan sur Joaquin Phoenix',
        },
    },    
    }

export default her;